remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
title: Nathan Van Vliet homepage
description: Bookmark this to keep an eye on my project updates!
my_link: "[Here is my Github](https://github.com/nathanvv21)"
